spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/job_tracking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # Автоматическое выполнение schema.sql при старте
      encoding: UTF-8